# Conda environment specification. The dependencies defined in this file will

# be automatically provisioned for managed runs. These include runs against

# the localdocker, remotedocker, and cluster compute targets.


# Note that this file is NOT used to automatically manage dependencies for the

# local compute target. To provision these dependencies locally, run:

# conda env update --file conda_dependencies.yml


# Details about the Conda environment file format:

# https://conda.io/docs/using/envs.html#create-environment-file-by-hand


# For managing Spark packages and configuration, see spark_dependencies.yml.


# Version of this configuration file's structure and semantics in AzureML.

# This directive is stored in a comment to preserve the Conda file structure.

# [AzureMlVersion] = 2


name: project_environment
dependencies:
  # The python interpreter version.

  # Currently Azure ML Workbench only supports 3.5.2 and later.

- python=3.6.2
  # Required by azureml-defaults, installed separately through Conda to

  # get a prebuilt version and not require build tools for the install.

- psutil=5.3

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-sdk[notebooks]
  - pynacl==1.2.1
  - scipy==1.0.0
  - scikit-learn==0.21.3
  - pandas==0.25.1
  - numpy==1.17.2
  - flask==1.1.1
  - gunicorn==19.9.0
  - flask-marshmallow==0.10.1
  - jupyter==1.0.0
  - bokeh==1.3.4
  - seaborn==0.9.0
  - statsmodels==0.10.1
  - psychrolib==2.1.1
  - joblib==0.13.2
  - pytest-cov==2.7.1
  - nbstripout==0.3.6
  - flask-cors==3.0.8
  - marshmallow==3.0.3
  - keras==2.2.5
  - tensorflow==1.14.0
  - azure-digitaltwins-core
  - azure-identity
  - azure-keyvault-secrets